<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WitelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('witels')->insert([
            [
                'nama'          => 'WITEL ACEH',
                'alias'         => 'WITEL ACEH',
                'id_regional'  => 1,
                'created_at'    => date('Y-m-d H:i:s'),
                'updated_at'    => date('Y-m-d H:i:s'),
            ],
            [
                'nama'       => 'WITEL BALIKPAPAN',
                'alias'      => 'WITEL BALIKPAPAN',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 6,
            ],
            [
                'nama'       => 'WITEL BANDUNG',
                'alias'      => 'WITEL BANDUNG',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 3,
            ],
            [
                'nama'       => 'WITEL BANJARMASIN',
                'alias'      => 'WITEL BANJARMASIN',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 6,
            ],
            [
                'nama'       => 'WITEL BATAM',
                'alias'      => 'WITEL BATAM',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 1,
            ],
            [
                'nama'       => 'WITEL CIREBON',
                'alias'      => 'WITEL CIREBON',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 3,
            ],
            [
                'nama'       => 'WITEL DENPASAR',
                'alias'      => 'WITEL DENPASAR',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 5,
            ],
            [
                'nama'       => 'WITEL DI YOGYAKARTA',
                'alias'      => 'WITEL DI YOGYAKARTA',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 4,
            ],
            [
                'nama'       => 'WITEL JAKARTA PUSAT',
                'alias'      => 'WITEL JAKARTA PUSAT',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 2,
            ],
            [
                'nama'       => 'WITEL JAKARTA BARAT',
                'alias'      => 'WITEL JAKARTA BARAT',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 2,
            ],
            [
                'nama'       => 'WITEL JAKARTA SELATAN',
                'alias'      => 'WITEL JAKARTA SELATAN',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 2,
            ],
            [
                'nama'       => 'WITEL JAKARTA TIMUR',
                'alias'      => 'WITEL JAKARTA TIMUR',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 2,
            ],
            [
                'nama'       => 'WITEL JAMBI',
                'alias'      => 'WITEL JAMBI',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 1,
            ],
            [
                'nama'       => 'WITEL JAYAPURA',
                'alias'      => 'WITEL JAYAPURA',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 7,
            ],
            [
                'nama'       => 'WITEL JEMBER',
                'alias'      => 'WITEL JEMBER',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 5,
            ],
            [
                'nama'       => 'WITEL KARAWANG',
                'alias'      => 'WITEL KARAWANG',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 3,
            ],
            [
                'nama'       => 'WITEL KEDIRI',
                'alias'      => 'WITEL KEDIRI',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 5,
            ],
            [
                'nama'       => 'WITEL KUDUS',
                'alias'      => 'WITEL KUDUS',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 4,
            ],
            [
                'nama'       => 'WITEL KUPANG',
                'alias'      => 'WITEL KUPANG',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 5,
            ],
            [
                'nama'       => 'WITEL LAMPUNG',
                'alias'      => 'WITEL LAMPUNG',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 1,
            ],
            [
                'nama'       => 'WITEL MADIUN',
                'alias'      => 'WITEL MADIUN',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 5,
            ],
            [
                'nama'       => 'WITEL MAKASSAR',
                'alias'      => 'WITEL MAKASSAR',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 7,
            ],
            [
                'nama'       => 'WITEL MALANG',
                'alias'      => 'WITEL MALANG',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 5,
            ],
            [
                'nama'       => 'WITEL MANADO',
                'alias'      => 'WITEL MANADO',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 7,
            ],
            [
                'nama'       => 'WITEL MATARAM',
                'alias'      => 'WITEL MATARAM',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 5,
            ],
            [
                'nama'       => 'WITEL MEDAN',
                'alias'      => 'WITEL MEDAN',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 1,
            ],
            [
                'nama'       => 'WITEL PADANG',
                'alias'      => 'WITEL PADANG',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 1,
            ],
            [
                'nama'       => 'WITEL PALANGKARAYA',
                'alias'      => 'WITEL PALANGKARAYA',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 6,
            ],
            [
                'nama'       => 'WITEL PALEMBANG',
                'alias'      => 'WITEL PALEMBANG',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 1,
            ],
            [
                'nama'       => 'WITEL PALU',
                'alias'      => 'WITEL PALU',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 7,
            ],
            [
                'nama'       => 'WITEL PARE-PARE',
                'alias'      => 'WITEL PARE-PARE',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 7,
            ],
            [
                'nama'       => 'WITEL PASURUAN',
                'alias'      => 'WITEL PASURUAN',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 5,
            ],
            [
                'nama'       => 'WITEL PEKANBARU',
                'alias'      => 'WITEL PEKANBARU',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 1,
            ],
            [
                'nama'       => 'WITEL PEMATANG SIANTAR',
                'alias'      => 'WITEL PEMATANG SIANTAR',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 1,
            ],
            [
                'nama'       => 'WITEL PONTIANAK',
                'alias'      => 'WITEL PONTIANAK',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 6,
            ],
            [
                'nama'       => 'WITEL SAMARINDA',
                'alias'      => 'WITEL SAMARINDA',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 6,
            ],
            [
                'nama'       => 'WITEL SEMARANG',
                'alias'      => 'WITEL SEMARANG',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 4,
            ],
            [
                'nama'       => 'WITEL SIDOARJO',
                'alias'      => 'WITEL SIDOARJO',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 5,
            ],
            [
                'nama'       => 'WITEL SINGARAJA',
                'alias'      => 'WITEL SINGARAJA',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 5,
            ],
            [
                'nama'       => 'WITEL SUKABUMI',
                'alias'      => 'WITEL SUKABUMI',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 3,
            ],
            [
                'nama'       => 'WITEL SURABAYA SELATAN',
                'alias'      => 'WITEL SURABAYA SELATAN',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 5,
            ],
            [
                'nama'       => 'WITEL SURABAYA UTARA',
                'alias'      => 'WITEL SURABAYA UTARA',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 5,
            ],
            [
                'nama'       => 'WITEL TANGERANG',
                'alias'      => 'WITEL TANGERANG',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 2,
            ],
            [
                'nama'       => 'WITEL TARAKAN',
                'alias'      => 'WITEL TARAKAN',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 6,
            ],
            [
                'nama'       => 'WITEL TASIKMALAYA',
                'alias'      => 'WITEL TASIKMALAYA',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'id_regional'  => 3,
            ],
        ]);
    }
}
